services:
  umans-gateway:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../../config:/var/lib/umans-gateway/config
